services:
  api:
    build: .
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  db:
    image: postgres:16
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  